-- 00_setup.sql : warehouse, budget guard, database, schemas, storage integration, stage, raw table
-- Run each statement separately in a Snowsight worksheet. Replace <AWS_ACCOUNT_ID> and <BUCKET_NAME>.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ECOM_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE RESOURCE MONITOR IF NOT EXISTS ECOM_RM
  WITH CREDIT_QUOTA = 5
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE ECOM_WH SET RESOURCE_MONITOR = ECOM_RM;

CREATE DATABASE IF NOT EXISTS ECOM_DB;
CREATE SCHEMA IF NOT EXISTS ECOM_DB.RAW;
CREATE SCHEMA IF NOT EXISTS ECOM_DB.MIRROR;

-- S3 access. The role name below is created by terraform (snowflake_access.tf).
CREATE STORAGE INTEGRATION IF NOT EXISTS ECOM_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/ecom-pipeline-snowflake-s3'
  STORAGE_ALLOWED_LOCATIONS = ('s3://<BUCKET_NAME>/raw/');

-- Copy STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID into terraform.tfvars, then `terraform apply`.
DESC INTEGRATION ECOM_S3_INT;

-- After terraform created the role:
CREATE OR REPLACE STAGE ECOM_DB.RAW.S3_RAW
  URL = 's3://<BUCKET_NAME>/raw/'
  STORAGE_INTEGRATION = ECOM_S3_INT
  FILE_FORMAT = (TYPE = PARQUET);

LIST @ECOM_DB.RAW.S3_RAW;   -- should show the DMS parquet files

CREATE TABLE IF NOT EXISTS ECOM_DB.RAW.CDC_EVENTS (
  SRC_TABLE STRING,
  OP        STRING,
  PAYLOAD   VARIANT,
  SRC_FILE  STRING,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
