-- 01: MIRROR tables (Fivetran-style _SYNCED_AT / _DELETED), stream on the raw table, one-time reload
-- Run each section in its own worksheet using Run All.

-- ---------- SECTION 0: context ----------
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ECOM_WH;
USE DATABASE ECOM_DB;

-- ---------- SECTION 1: mirror tables ----------
CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.CUSTOMERS (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.SELLERS (
  SELLER_ID STRING,
  SELLER_ZIP_CODE_PREFIX STRING,
  SELLER_CITY STRING,
  SELLER_STATE STRING,
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.PRODUCTS (
  PRODUCT_ID STRING,
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_NAME_LENGHT INT,
  PRODUCT_DESCRIPTION_LENGHT INT,
  PRODUCT_PHOTOS_QTY INT,
  PRODUCT_WEIGHT_G INT,
  PRODUCT_LENGTH_CM INT,
  PRODUCT_HEIGHT_CM INT,
  PRODUCT_WIDTH_CM INT,
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.PRODUCT_CATEGORY_NAME_TRANSLATION (
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_CATEGORY_NAME_ENGLISH STRING,
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.ORDERS (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TIMESTAMP TIMESTAMP_NTZ,
  ORDER_APPROVED_AT TIMESTAMP_NTZ,
  ORDER_DELIVERED_CARRIER_DATE TIMESTAMP_NTZ,
  ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP_NTZ,
  ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP_NTZ,
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.ORDER_ITEMS (
  ORDER_ID STRING,
  ORDER_ITEM_ID INT,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_DATE TIMESTAMP_NTZ,
  PRICE NUMBER(10,2),
  FREIGHT_VALUE NUMBER(10,2),
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ECOM_DB.MIRROR.ORDER_PAYMENTS (
  ORDER_ID STRING,
  PAYMENT_SEQUENTIAL INT,
  PAYMENT_TYPE STRING,
  PAYMENT_INSTALLMENTS INT,
  PAYMENT_VALUE NUMBER(10,2),
  _SYNCED_AT TIMESTAMP_NTZ,
  _DELETED BOOLEAN DEFAULT FALSE
);

-- ---------- SECTION 2: stream on raw table + one-time reload ----------
-- (the stream only sees rows added AFTER it is created, so we reload once)
CREATE STREAM IF NOT EXISTS ECOM_DB.RAW.CDC_STREAM ON TABLE ECOM_DB.RAW.CDC_EVENTS APPEND_ONLY = TRUE;

TRUNCATE TABLE ECOM_DB.RAW.CDC_EVENTS;

COPY INTO ECOM_DB.RAW.CDC_EVENTS (SRC_TABLE, OP, PAYLOAD, SRC_FILE)
FROM (
  SELECT REGEXP_SUBSTR(METADATA$FILENAME, 'public/([^/]+)/', 1, 1, 'e', 1),
         COALESCE($1:Op::STRING, 'I'),
         $1,
         METADATA$FILENAME
  FROM @ECOM_DB.RAW.S3_RAW
)
PATTERN = '.*public/.*[.]parquet'
FILE_FORMAT = (TYPE = PARQUET)
FORCE = TRUE;

