-- 03: scheduled load + merge. Root task must be suspended before changing the child.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ECOM_WH;
USE DATABASE ECOM_DB;
USE SCHEMA ECOM_DB.RAW;

CREATE OR REPLACE TASK ECOM_DB.RAW.T_LOAD_S3
  WAREHOUSE = ECOM_WH
  SCHEDULE = '10 MINUTE'
AS
  COPY INTO ECOM_DB.RAW.CDC_EVENTS (SRC_TABLE, OP, PAYLOAD, SRC_FILE)
  FROM (
    SELECT REGEXP_SUBSTR(METADATA$FILENAME, 'public/([^/]+)/', 1, 1, 'e', 1),
           COALESCE($1:Op::STRING, 'I'),
           $1,
           METADATA$FILENAME
    FROM @ECOM_DB.RAW.S3_RAW
  )
  PATTERN = '.*public/.*[.]parquet'
  FILE_FORMAT = (TYPE = PARQUET);

CREATE OR REPLACE TASK ECOM_DB.RAW.T_MERGE_MIRROR
  WAREHOUSE = ECOM_WH
  AFTER ECOM_DB.RAW.T_LOAD_S3
  WHEN SYSTEM$STREAM_HAS_DATA('ECOM_DB.RAW.CDC_STREAM')
AS
  CALL ECOM_DB.MIRROR.SP_MERGE_ALL();

ALTER TASK ECOM_DB.RAW.T_MERGE_MIRROR RESUME;
ALTER TASK ECOM_DB.RAW.T_LOAD_S3 RESUME;
