USE ROLE ACCOUNTADMIN;
USE DATABASE ECOM_DB;

-- events received from DMS
SELECT SRC_TABLE, OP, COUNT(*) AS ROWS_CNT FROM ECOM_DB.RAW.CDC_EVENTS GROUP BY 1, 2 ORDER BY 1, 2;

-- mirror counts (deleted rows are kept with _DELETED = TRUE)
SELECT COUNT(*) AS LIVE_ORDERS FROM ECOM_DB.MIRROR.ORDERS WHERE NOT _DELETED;
SELECT ORDER_STATUS, COUNT(*) FROM ECOM_DB.MIRROR.ORDERS WHERE NOT _DELETED GROUP BY 1 ORDER BY 2 DESC;

-- demo orders created by data/demo_insert.py
SELECT ORDER_ID, ORDER_STATUS, _DELETED, _SYNCED_AT FROM ECOM_DB.MIRROR.ORDERS
WHERE ORDER_ID LIKE 'demo%' ORDER BY _SYNCED_AT DESC;

-- task health
SELECT NAME, STATE, SCHEDULED_TIME, ERROR_MESSAGE
FROM TABLE(ECOM_DB.INFORMATION_SCHEMA.TASK_HISTORY(RESULT_LIMIT => 20))
WHERE NAME IN ('T_LOAD_S3', 'T_MERGE_MIRROR') ORDER BY SCHEDULED_TIME DESC;
