-- 99: remove everything on the Snowflake side
USE ROLE ACCOUNTADMIN;
ALTER TASK IF EXISTS ECOM_DB.RAW.T_LOAD_S3 SUSPEND;
ALTER TASK IF EXISTS ECOM_DB.RAW.T_MERGE_MIRROR SUSPEND;
DROP DATABASE IF EXISTS ECOM_DB;
DROP WAREHOUSE IF EXISTS ECOM_WH;
DROP RESOURCE MONITOR IF EXISTS ECOM_RM;
DROP INTEGRATION IF EXISTS ECOM_S3_INT;
